apiVersion: v1
kind: Service
metadata:
  name: {{ include "camunda-app-poc.fullname" . }}
  labels:
    {{- include "camunda-app-poc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    {{- include "camunda-app-poc.selectorLabels" . | nindent 6 }}
