version: '3.8'

services:
  camunda-app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - ZEEBE_CLIENT_CLOUD_REGION=${ZEEBE_CLIENT_CLOUD_REGION}
      - ZEEBE_CLIENT_CLOUD_CLUSTER_ID=${ZEEBE_CLIENT_CLOUD_CLUSTER_ID}
      - ZEEBE_CLIENT_CLOUD_CLIENT_ID=${ZEEBE_CLIENT_CLOUD_CLIENT_ID}
      - ZEEBE_CLIENT_CLOUD_CLIENT_SECRET=${ZEEBE_CLIENT_CLOUD_CLIENT_SECRET}
    networks:
      - camunda-network

networks:
  camunda-network:
    driver: bridge
