apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "camunda-app-poc.fullname" . }}
  labels:
    {{- include "camunda-app-poc.labels" . | nindent 4 }}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.49.240-192.168.49.250
